name: First WorkFlow

on: 
  push: 
      branches: 
         - main


jobs:
   example-jop:
        runs-on: ubuntu-latest

        steps:
          - name: print a welcome meassge
            run: echo "Welcome To Our First Workflow"
          - name: Checkout repo
            uses: actions/checkout@v7.0.0
          - name: list repo files
            run: ls -la
